// METODO GET E POST

//GET:
/*
    ENVIA OS DADOS POR MEIO DA URL PARA O BACKEND

    PERIGOSO PARA CADASTRO DE SENHAS POR CONTA DA EXPOSIÇÃO
*/

//POST:

/*

    O MÉTODO POST PASSA OS DADOS DE OUTRA FORMA QUE NÃO PELA URL

*/

//app.post para formulários